environment:
  github_auth_token:
    secure: 1nfb9SLjo61snT5F5LIQp7IROP99WveRGt5IzVUPRaefxRHEjQkV8faa+mB7MitN
before_build:
 - nuget restore
build_script:
 - echo %xunit20%
 - msbuild /verbosity:quiet "codecov-on-appveyor.sln"
